### ISSUE TITLE
Reading zip (not gzip) files in Spark

### ISSUE THREAD

**Issue by rsoni1** [BIDS-collaborative/dlab-finance#5] opened 2015-03-03 16:29 UTC
Any pointers on how best to read gzip files in spark. I read that the sc.textFile() would decompress but it isn't. For now I am testing reading from an uncompressed test datafile.

**Comment by davclark** [comment] 2015-03-03 19:32
My understanding from talking to AMP lab folks was that this is NOT currently supported - but I see mailing list posts that it is. I'm pinging Jey.

**Comment by davclark** [comment] 2015-03-03 19:37
I also see that you're not (yet) committing code to this repo... even if we're just building up basic functionality, it's easier to debug if we have the exact same script!

**Comment by rsoni1** [comment] 2015-03-03 20:44
I finally fixed my git issue and have committed code that you can run using the runjob script.

**Comment by jey** [comment] 2015-03-03 20:53
I'm not able to reproduce the problem, the following works for me as expected:

```python
print sc.textFile("test.txt.gz").count()
```

**Comment by jey** [comment] 2015-03-03 22:11
@rsoni1, Could you share the code you're using that doesn't work, and any error messages you encounter?

**Comment by davclark** [comment] 2015-03-03 22:36
Also - just to chime in - Jey, are you able to log in and run jobs on Savio? I'm happy to walk through that if it's not obvious.

**Comment by rsoni1** [comment] 2015-03-03 22:50
messages : https://github.com/berkeley-dsc/dlab-finance/issues/1

code : https://github.com/berkeley-dsc/dlab-finance under the scratch dir.
File taq.py

If you are unable to access the repo let me know and I will send you the
code snippet.

R

**Comment by rsoni1** [comment] 2015-03-03 22:51
Ah sorry wrong thread. this earlier note was meant for another issue not
the zip.

I realized that the zip didn't work since the file was in a .zip format.
and not .gz. I compressed using gzip and gave it a shot. It was taking too
long so I haven't tried to debug yet. But I will try again using the gzip
format.

Ritesh

**Comment by jey** [comment] 2015-03-03 22:59
@davclark, I've created my OTP but I haven't tried going further than that yet

**Comment by davclark** [comment] 2015-03-04 23:18
FYI - @jey thinks we'll need to use Hadoop files directly to explain how to unzip the files. We'll plan to sit down and work through this as soon as we can!

**Comment by davclark** [comment] 2015-03-06 00:46
Hey guys, @jey helped identify a jar that works with later versions of Spark. You can find it [here](/berkeley-dsc/dlab-finance/tree/master/read-zip).

You can run this with sbatch, but it doesn't work with Spark 1.0. I asked the BRC folks to accelerate on getting Spark 1.2+ installed (ideally 1.3).

**Comment by davclark** [comment] 2015-03-16 16:31
From @nital:

> I tried rebuilding Maven with following flags (as per notes found on spark
> page), but still running out heap space when executing example. The node I have had 16GB RAM.
> ```
> export MAVEN_OPTS="-Xmx4g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m"
> cd com-cotdp-hadoop-master/
> mvn clean package
> ```

> If you are familiar with Maven, is above method of building the jar okay?

@nital: Did you try using the existing jar in the read-zip folder?

In any case, this is a question for @jey - I'm no expert on Maven. Are you working now on SAVIO or Softlayer? I'm guessing Softlayer, as I think SAVIO is still on Spark 1.0, and needs to be upgraded still.

**Comment by jey** [comment] 2015-03-16 16:47
Hi @nital, could you elaborate on how you're executing the example, and which example? Do you get the errors from building the JAR, or do you get the errors while running the example?

If `mvn` prints out no errors and exits with code `0`, then it successfully built the project.

**Comment by nitalpatwa** [comment] 2015-03-16 20:34
Jey,

I am referring to example.py in the link below - They are authored by you
it seems.

https://github.com/berkeley-dsc/dlab-finance/tree/master/read-zip

I took the source from this comment in above example:

# The `hadoop-zip.jar` file was built from the code at:
#   https://github.com/cotdp/com-cotdp-hadoop

And  built the JAR  successfully with Maven with following options:

export MAVEN_OPTS="-Xmx4g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m"

I had also built JAR without specifying any options earlier.


Then I went to Spark for a file that was 300MB compressed and 2.5GB
uncompressed. This file is
/global/scratch/aculich/mirror/EQY_US_ALL_TRADE/EQY_US_ALL_TRADE_2013/EQY_US_ALL_TRADE_201312/EQY_US_ALL_TRADE_20131218.zip


Granted, I did above on a different cloud where I carry a 16GB RAM on
driver node and 3 worker nodes.
And I had moved above file in the HDFS.

I had simply modified the example file from above github area to point the
"data" to the HDFS filename.


During execution the JAVA Heap Space is exhausted.
So rdd reading is not completed.

Nital

**Comment by jey** [comment] 2015-03-16 23:01
Hi @nitalpatwa, thanks a lot for the detailed problem report. Could you please try increasing the executor and driver memory settings by changing your launch command to something like:
```
spark-submit --executor-memory 8G --driver-memory 8G --jars hadoop-zip.jar example.py
```

**Comment by jey** [comment] 2015-03-16 23:03
(The default memory settings are 1G each, so Spark probably is unable to fit the uncompressed ZIP file in memory.)

**Comment by jey** [comment] 2015-03-16 23:05
You probably also want to change the last line of `example.py` to change "collect()" to instead "count()" so that it won't try to send the whole RDD contents to the driver process:

**Comment by nitalpatwa** [comment] 2015-03-17 01:59
Jey,

Thank you.

The memory related flags you suggested did make the heap memory issue go
away, but it was replaced with
OutOfMemoryError: Requested array size exceeds VM limit.


[root@npatwa91 ~]#  spark-submit --jars hadoop-zip.jar --executor-memory 2G
--driver-memory 4G example.py

15/03/16 20:16:52 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.OutOfMemoryError: Requested array size exceeds VM limit

Nital

**Comment by nitalpatwa** [comment] 2015-03-17 02:41
I had manually converted .zip to .gz by using unzip and then gzip.
Spark was able to read such .gz file natively.
But when I ran count() on the taq file with over 700 million records, and
7GB gzipped file size,
it ran for 30 minutes but with ill-fate.

py4j.protocol.Py4JJavaError: An error occurred while calling o34.collect.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0
in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage
1.0 (TID 1, localhost): java.io.IOException: stored gzip size doesn't match
decompressed size
        at
org.apache.hadoop.io.compress.zlib.BuiltInGzipDecompressor.executeTrailerState(BuiltInGzipDecompressor.java:389)


Google search on above message suggests that there was a bug in hadoop that
printed that message for compressed files > 4GB.

http://www.cloudera.com/content/cloudera/en/documentation/cdh4/latest/CDH4-Release-Notes/cdh4ki_topic_2_1.html

 It saided that it was fixed in CDH4.2.0.
Now this raises interesting points. Does the spark carry this fix? Is it
also fixed in the the Apache Hadoop version that is NOT cloudera version?

Nital

**Comment by jey** [comment] 2015-03-17 20:19
I think the simplest thing will be to run a one-time batch job that converts all the input files to a splittable compression format such as LZO. "Splitable" means that a single input file can produce multiple Spark partitions.

http://blog.cloudera.com/blog/2009/11/hadoop-at-twitter-part-1-splittable-lzo-compression/

**Comment by nitalpatwa** [comment] 2015-03-17 21:04
I agree. Thanks for sending a very useful link. Indeed.
Thanks
Nital

**Comment by jey** [comment] 2015-03-18 00:58
Looks like the current version of Hadoop LZO is at https://github.com/twitter/hadoop-lzo

BTW, do you know how to create a batch job that could perform the conversion? I believe a SLURM batch script may be the way to go, but I'm unfamiliar with the details.

**Comment by nital** [comment] 2015-03-18 05:17
Hi All,
Please remove me from the mailing list. This isnt relevant to me.


Nital Shah
Tata Consultancy Services
Mailto: nital.shah@tcs.com
Website: http://www.tcs.com
____________________________________________
Experience certainty.   IT Services
                        Business Solutions
                        Consulting
____________________________________________

**Comment by davclark** [comment] 2015-03-18 15:10
Oops - I think that was my bad, Nital Shah, but this isn't a mailing list. This is a github issue. I'll try editing your name above, but you may need to "unwatch" the thread.

**Comment by rsoni1** [comment] 2015-04-14 16:37
tried a small test with LZ4 compression and Spark is unable to decode files.

Could this be related to the following warnings at Spark startup
15/04/14 08:58:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/04/14 08:58:10 WARN LoadSnappy: Snappy native library not loaded

**Comment by jey** [comment] 2015-04-14 17:23
Have you tried googling "spark lz4" and related queries to try to resolve the issue? Also, the output you pasted includes no error messages regarding failure in reading files.

**Comment by jey** [comment] 2015-04-15 21:02
(BTW: nope, the problem is most likely not related to those warnings.)

**Comment by surendralalwani** [comment] 2015-09-11 17:22
Does example.py still work?

I get this error

15/09/11 17:15:53 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
        at com.cotdp.hadoop.ZipFileRecordReader.initialize(ZipFileRecordReader.java:68)
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:133)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:104)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:66)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
        at org.apache.spark.scheduler.Task.run(Task.scala:70)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by davclark** [comment] 2015-09-12 18:09
Who is @surendralalwani? I assume you are running this on Savio and initializing the spark context correctly? Can you do a spark "hello world" on Savio for example?

**Comment by surendralalwani** [comment] 2015-09-12 23:07
Hi

I started to using Spark recently and had come up with a situation where I
had to read zip files. I am using spark 1.4.1 with hadoop 2.6, standalone
on my desktop.

I am a software professional at Thomson Reuters.

Thanks
Surendra

**Comment by davclark** [comment] 2015-09-13 20:02
Interesting. I guess this points to a need to get this code out into a small, self-contained repo that is generally useful. For reference, I think the code for reading zipfiles is pretty simple, and it was written targeting Spark 1.3. I don't know if the API changed for 1.4 in a way that would break this code.

The jar was built from this code (as you could see from the above discussion):

https://github.com/cotdp/com-cotdp-hadoop

But it appears unmaintained (the blog just throws a database error!). Are you at a level where you could try rebuilding that code against whatever versions of hadoop + spark you are using? I might also suggest that we move this discussion over there if we run into trouble? If the author is unresponsive, I'm happy to fork into the D-Lab org and make it slightly more maintained.

**Comment by surendralalwani** [comment] 2015-09-13 21:20
As rightly suggested, I opened a new issue 

https://github.com/cotdp/com-cotdp-hadoop/issues/1

Yes, I did change the pom.xml to use hadoop common 2.6.0 and created the jar, still got the same error.

**Closed** 2015-10-02 18:08 UTC
